version: "3.3"
services:
  httpd:
    image: httpd:2.4
    container_name: aws-robot-delivery-challenge-browser
    volumes:
      - "${AWS_WEB_UI_DIR}:/usr/local/apache2/htdocs/:ro"
    ports:
      - 8080:80